package no.ntnu.idatx2003.oblig4.cardgame;

import java.util.ArrayList;
import java.util.List;

/**
 * The DeckOfCards class represents a deck of playing cards. The deck is a standard deck of 52
 * playing cards, with 4 suits and 13 faces. The class is implemented using the List and ArrayList
 * libraries.
 *
 * @author Johannes Nupen Theigen
 * @version 0.0.1
 * @since 03.05.2025
 */
public class DeckOfCards {

  private final List<PlayingCard> cards;
  private final char[] suits = {'S', 'H', 'D', 'C'};

  /**
   * Initializes a new DeckOfCards object with a standard deck of
   * 52 playing cards (4 suits and 13 faces).
   * The cards are stored in an ArrayList and generated in
   * the constructor using the generateDeck method.
   */
  public DeckOfCards() {
    cards = new ArrayList<>();
    generateDeck(); // Generates a standard deck of 52 playing cards and adds them to the deck
  }

  /**
   * Generates a standard deck of 52 playing cards. The deck is
   * generated by iterating over the suits
   * and faces of the cards and adding them to the deck.

   * @return true if the deck was successfully generated, false otherwise
   */
  public boolean generateDeck() {
    boolean deckGenerated = false;

    if (!cards.isEmpty()) {
      return deckGenerated;
    }
    for (char suit : suits) {
      for (int face = 1; face <= 13; face++) {
        cards.add(new PlayingCard(suit, face));
      }
    }
    deckGenerated = true;
    return deckGenerated;
  }
}